staticrangesumqueries: staticrangesumqueries.cpp
	g++ staticrangesumqueries.cpp -o staticrangesumqueries  -Wall -Wextra -pedantic -std=c++17

run: staticrangesumqueries
	./staticrangesumqueries
	rm staticrangesumqueries
