restaurantCustomers: restaurantCustomers.cpp
	g++ restaurantCustomers.cpp -o restaurantCustomers  -Wall -Wextra -pedantic -std=c++17

run: restaurantCustomers
	./restaurantCustomers
	rm restaurantCustomers
